#!/usr/bin/env python3
"""The t27b steward's decisions live in t27, not in Python (#6198).

Owner's rule, 2026-10-05 (AGENTS.md "t27b is written in t27"): t27b and the
tools that measure it are written in t27. `tri t27b delta` used to classify
each per-spec transition with a hand-written Python `if` chain; that logic
now lives in specs/tri/t27b/steward.t27 and reaches Python only as
gen/c/tri/t27b/steward.c, generated by `t27c gen-c` and loaded by
scripts/tri_loop/t27b_rules.py.

Checks:
  1. the generated C, built with the spec's own test runner, passes the
     spec's tests;
  2. a mutant of that C (pct_tenths rounds down) fails them -- the mutation
     control, so check 1 can go red;
  3. the loader answers what the spec says for the cases the lab produces;
  4. t27b.py's delta has no verdict tuple of its own any more;
  5. if a t27c is present, `t27c gen-c` of the spec is byte-identical to the
     committed C (in CI there is no t27c in this job, and the output says
     "not checked" rather than "ok").
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "specs/tri/t27b/steward.t27"
GEN = ROOT / "gen/c/tri/t27b/steward.c"
TOOL = ROOT / "scripts/tri_loop/t27b.py"
fails = 0


def check(ok, what):
    global fails
    print(("ok      " if ok else "FAIL    ") + what)
    fails += 0 if ok else 1


def runs_tests(src: Path) -> tuple[int, str]:
    with tempfile.TemporaryDirectory() as tmp:
        exe = os.path.join(tmp, "steward_tests")
        b = subprocess.run([os.environ.get("CC", "cc"), "-DT27_TEST_MAIN", "-w", "-o", exe, str(src)],
                           capture_output=True, text=True)
        if b.returncode != 0:
            return -1, b.stderr[:300]
        r = subprocess.run([exe], capture_output=True, text=True)
        return r.returncode, r.stdout.strip()


code, out = runs_tests(GEN)
check(code == 0 and "38 tests passed" in out, f"the generated C passes the spec's tests ({code}: {out})")

text = GEN.read_text()
needle = "return (((in_ref * 1000) + (reference / 2)) / reference);"
check(text.count(needle) == 1, "mutation: the rounding to remove is present exactly once")
with tempfile.TemporaryDirectory() as tmp:
    mutant = Path(tmp) / "steward.c"
    mutant.write_text(text.replace(needle, "return ((in_ref * 1000) / reference);"))
    code, out = runs_tests(mutant)
    check(code not in (0, -1), f"mutation: a C that rounds down fails the spec's tests (exit {code})")

sys.path.insert(0, str(ROOT / "scripts/tri_loop"))
import t27b_rules as r  # noqa: E402

cases = [
    (("pass", "pass", "pass", "frontend", 3, 0), "REGRESSED"),
    (("pass", "pass", "pass", "pass_vacuous", 3, 0), "REGRESSED"),
    (("pass", "pass", "blocked", "fail", 0, 1), "NEW-MISMATCH"),
    (("pass", "pass", "mismatch", "fail", 0, 1), None),
    (("pass", "pass", "blocked", "pass", 0, 0), "GAINED"),
    (("pass", "pass", "pass", "pass", 2, 0), "CHECK-LOST"),
    (("blocked", "pass", "blocked", "pass", 0, 1), "REF-MOVED"),
    (("fail", "fail", "blocked", "pass", 0, 1), None),
]
got = [r.delta(*a) for a, _ in cases]
check(got == [w for _, w in cases], f"the loader answers what the spec says ({got})")
check([d for d in r.DELTAS if d and r.is_red(d)] == ["REGRESSED", "NEW-MISMATCH", "CHECK-LOST"],
      "red transitions come from delta_is_red")
check((r.pct(56, 648), r.pct(75, 657), r.pct(0, 0)) == ("8.6", "11.4", "0.0"), "the honest percentage")
try:
    r.verdict("passed")
    check(False, "an unknown lab verdict is an error, not a guess")
except r.RulesUnavailable:
    check(True, "an unknown lab verdict is an error, not a guess")

rcases = [
    (("pass", "pass", "pass", True, True), None),
    (("pass", "pass", "pass_vacuous", False, True), "VACUITY MEASURED"),
    (("pass", "pass", "pass_vacuous", True, True), "UNEXPECTED FAILURE"),
    (("pass_vacuous", "pass", "pass", True, True), "UNEXPECTED PASS"),
    (("blocked", "pass", "pass", True, True), "UNEXPECTED PASS"),
    (("blocked", "pass", "blocked", True, False), "MOVED"),
    (("blocked", "fail", "blocked", True, True), "STALE"),
    (("blocked", "not run", "blocked", True, True), "UNJUDGED"),
    (("missing", "pass", "fail", True, True), None),
    (("missing", "pass", "fail", True, False), "MOVED"),
]
got = [r.entry(*a) for a, _ in rcases]
check(got == [w for _, w in rcases], f"the ratchet entry finding is the spec's ({got})")
check([k for k in r.RATCHETS if k and r.ratchet_is_red(k)]
      == ["UNEXPECTED FAILURE", "UNEXPECTED PASS", "STALE", "UNLISTED", "OVER CAP", "BAD REASON"],
      "red ratchet findings come from ratchet_is_red")
check((r.unlisted("pass", False), r.unlisted("pass", True), r.unlisted("fail", False)) == (True, False, False),
      "unlisted: only a reference pass the ledger does not name")
check((r.over_cap(5, 5), r.over_cap(6, 5), r.over_cap(0, None), r.over_cap(0, "7"), r.over_cap(0, True))
      == (False, True, True, True, True), "over_cap: the cap only moves down; no whole-number cap is over")

check((r.bless_reason("fail", "reference-bug"), r.bless_reason("frontend", None), r.bless_reason("mismatch", None),
       r.bless_reason("timeout", "bogus")) == ("reference-bug", "unimplemented", None, None),
      "bless: a written reason is kept, a rejected construct is unimplemented, a defect is refused")
check((r.cap_rises(6, 5), r.cap_rises(5, 5), r.cap_rises(9, None)) == (True, False, False),
      "bless: the cap may fall, never rise; a ledger without one sets it")

tool = TOOL.read_text()
body = tool[tool.index("def delta("):tool.index("def previous_run(")]
check('("fail", "mismatch", "crash")' not in body and "rules().delta(" in body,
      "t27b.py delta asks the spec and keeps no verdict tuple of its own")
body = tool[tool.index("def ratchet("):tool.index("def bless(")]
check("r.entry(" in body and "got in PASSES" not in body and "want not in PASSES" not in body,
      "t27b.py ratchet asks the spec and keeps no branch of its own")
body = tool[tool.index("def bless("):tool.index("def dump_ledger(")]
check("r.bless_reason(" in body and "r.cap_rises(" in body and "UNIMPLEMENTED" not in tool and "PASSES" not in tool,
      "t27b.py bless asks the spec and keeps no verdict tuple of its own")

t27c = os.environ.get("TRI_T27C") or next(
    (str(p) for p in (ROOT / "target/release/t27c", ROOT / "target/debug/t27c") if os.access(p, os.X_OK)), None)
if t27c:
    g = subprocess.run([t27c, "gen-c", str(SPEC)], capture_output=True, text=True)
    check(g.returncode == 0 and g.stdout == text,
          f"gen/c/tri/t27b/steward.c is `t27c gen-c {SPEC.relative_to(ROOT)}` byte for byte")
else:
    print("not checked: no t27c here, so gen/c/tri/t27b/steward.c is not compared with a fresh gen-c")

print()
print(("PASS" if fails == 0 else "FAIL") + f": {fails} failure(s)")
sys.exit(1 if fails else 0)
